name: Setup Environment
description: Composite action to checkout code, setup Bun, and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2 

    - name: Install dependencies
      run: bun install
      shell: bash 
