services:
  app:
    container_name: app-sample
    build:
      args:
        - APP_PORT=${APP_PORT}
      env_file:
        - .env
      depends_on:
        - postgres
        - redis
      networks:
        - sample-app-network

  postgres:
    container_name: postgres-sample
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-sample-data:/var/lib/postgresql/data
    networks:
      - sample-app-network
  
  redis:
    container_name: redis-sample
    image: redis:7.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT:6379
    volumes:
      - redis-sample-data:/data
    networks:
      - sample-app-network

volumes:
  postgres-sample-data:
  redis-sample-data:

networks:
  sample-app-network: