name: CodeQL Analysis

on:
  schedule:
    - cron: '0 17 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    permissions:
      security-events: write
    
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
          queries: +security-extended, +security-and-quality

      - name: Build Library
        run: bun run build:lib

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
