name: E2e Testing

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'e2e/**'
      - 'package.json'
      - 'bun.lock'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Library
        run: bun run build:lib

      - name: Integration Tests
        run: bun run test:integration

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Library
        run: bun run build:lib

      - name: E2e-Tests
        run: bun run test:e2e
