name: "Release"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Library
        run: bun run build:lib

      - name: Publish to npm
        run: |
          cd lib
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
