name: Release (GitHub & NPM)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (optional)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Environment
        uses: ./.github/actions/setup

      - name: Initialize Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup NPM Authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Release-It
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "auto" ]; then
            bun run release --ci
          else
            bun run release ${{ github.event.inputs.release_type }} --ci
          fi
